// GENERATED by backend/scripts/export_measured.py — do not edit by hand.
//
// Every number here was produced by a run of the backend and can be traced to an
// artifact under backend/artifacts/. Prose belongs in data.ts; this file is only
// measurements, so that a figure on the page can never drift from the run that
// produced it.
//
// Two corpora, kept apart on purpose:
//
//   ROUTERBENCH — 36,497 real prompts x 11 real commercial models,
//   401,467 graded cells, $333.79 of inference already paid for by
//   whoever collected it. Carries release dates, which is what makes the decay
//   curve a retrospective rather than a simulation.
//
//   CHUTES — the 13 models the product actually routes over. No public benchmark
//   grades those checkpoints, so each slot is bound to a measured stand-in
//   (backend/rollingbench/catalog.py, CHUTES_PROXY) and the router is trained on
//   that model's real per-item outcomes. Prices are the live Chutes list.
//   PROXY-BACKED: read as "what this pool would do if each model behaves like its
//   stand-in", not as a measurement of a Chutes endpoint.

export const ROUTERBENCH = {
  items: 36497,
  models: 11,
  gradedCells: 401467,
  inferenceUsd: 333.79,
  /** Share of model pairs scoring identically on the same item. */
  tieRate: 0.5784,
} as const;

/**
 * A router fitted once, replayed over 26 weeks of a pool that really grew.
 * `frozen` never updates and cannot select a model released after its cut-off;
 * `rolling` absorbs each week's outcomes and onboards new models. Values are
 * normalised regret against the per-item oracle, so lower is better.
 */
export const DECAY = {
    "weeks": [
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      14,
      16,
      18,
      20,
      22,
      24
    ],
    "frozen": [
      1.032,
      1.05,
      0.978,
      0.941,
      1.008,
      0.948,
      1.024,
      1.923,
      1.837,
      2.223,
      2.373,
      1.882,
      2.182
    ],
    "rolling": [
      1.032,
      1.049,
      1.028,
      1.028,
      0.991,
      1.017,
      1.002,
      1.303,
      1.125,
      1.106,
      1.322,
      1.04,
      1.022
    ],
    "frozenDecay": 1.022,
    "rollingDecay": 0.02,
    "weekCrossedBelowBestSingle": 5,
    "shareFromNewModels": 0.987
  } as const;

/** The pool the product serves. Proxy-backed — see the header. */
export const CHUTES_POOL = {
  proxyBacked: true,
  models: 13,
  /** Items every one of the 13 answered, used for every comparison below. */
  denseCoreItems: 3541,
  testItems: 1239,
  /**
   * The benchmarks the *dense core* covers — the ones every model answered, and
   * therefore the only ones any comparison here is computed on. Deliberately not
   * `01_pool.json`'s task list, which spans the whole corpus including tasks only
   * the small models were run on; quoting that number would overstate the breadth
   * behind every figure on this page.
   */
  tasks: [
    "aime",
    "arenahard",
    "arenahard_coding",
    "arenahard_creative_writing",
    "arenahard_math",
    "gpqa",
    "livecodebench",
    "livemathbench",
    "mmlupro"
  ],
  /** Every task in the corpus, for context only. Nothing is measured on all of them. */
  corpusTasks: [
    "aime",
    "arc-agi",
    "arcc",
    "arenahard",
    "arenahard_coding",
    "arenahard_creative_writing",
    "arenahard_math",
    "bbh",
    "emorynlp",
    "finqa",
    "gpqa",
    "hle",
    "humaneval",
    "kandk",
    "korbench",
    "livecodebench",
    "livemathbench",
    "math500",
    "mathbench",
    "mbpp",
    "medqa",
    "meld",
    "mmlupro",
    "simpleqa",
    "swe-bench",
    "tau2",
    "winogrande"
  ],
  /** The dial, calibrated on this pool rather than inherited. */
  lamCost: 0.2,
} as const;

/**
 * What routing this pool is worth, over 8 random splits.
 *
 * Two baselines, because they say different things and only quoting the first
 * would flatter the router:
 *
 *   vsFrontierModel — against the highest-quality model, which is what a team
 *   that "just uses the best one" is doing today.
 *
 *   vsBestSingleModel — against the single model that is actually optimal on this
 *   pool once price is counted. A harder opponent, and the honest one. On this
 *   pool it is Qwen/Qwen3-235B-A22B-Thinking-2507-TEE, which beats the
 *   highest-quality model on quality *and* price.
 */
export const SAVINGS = {
  proxyBacked: true,
  vsFrontierModel: {
    model: "zai-org/GLM-5.2-TEE",
    savings: 0.7957,
    savingsSe: 0.0031,
    qualityRetained: 0.9779,
    qualityRetainedSe: 0.0043,
  },
  vsBestSingleModel: {
    model: "Qwen/Qwen3-235B-A22B-Thinking-2507-TEE",
    savings: 0.195,
    savingsSe: 0.0137,
    qualityRetained: 0.9862,
    qualityRetainedSe: 0.0045,
  },
  /** The ceiling: a per-item oracle that always picks the right model. */
  oracleQuality: 0.9734,
  routerQuality: 0.8289,
  frontierQuality: 0.8309,
  tierMix: {
    "open": 0.0726,
    "mid": 0.9104,
    "frontier": 0.0169
  },
} as const;

/** Per model, on held-out items at the calibrated dial. Proxy-backed. */
export const POOL_MEASURED = [
    {
      "id": "Nemotron-3-Nano-Omni-30B-TEE",
      "quality": 0.4895,
      "share": 0.0363,
      "costPerCall": 0.000634,
      "uniquelyCorrect": 0,
      "proxyId": "NVIDIA-Nemotron-Nano-9B-v2"
    },
    {
      "id": "unsloth/Mistral-Nemo-Instruct-2407-TEE",
      "quality": 0.222,
      "share": 0.0,
      "costPerCall": 0.000106,
      "uniquelyCorrect": 2,
      "proxyId": "Llama-3.1-8B-Instruct"
    },
    {
      "id": "deepseek-ai/DeepSeek-V4-Flash-0731-TEE",
      "quality": 0.5319,
      "share": 0.0105,
      "costPerCall": 0.002149,
      "uniquelyCorrect": 1,
      "proxyId": "DeepSeek-R1-0528-Qwen3-8B"
    },
    {
      "id": "google/gemma-4-31B-turbo-TEE",
      "quality": 0.2603,
      "share": 0.0,
      "costPerCall": 0.000177,
      "uniquelyCorrect": 1,
      "proxyId": "gemma-2-9b-it"
    },
    {
      "id": "Qwen/Qwen3-32B-TEE",
      "quality": 0.5351,
      "share": 0.0258,
      "costPerCall": 0.002578,
      "uniquelyCorrect": 0,
      "proxyId": "Qwen3-8B"
    },
    {
      "id": "Qwen/Qwen3-235B-A22B-Thinking-2507-TEE",
      "quality": 0.8341,
      "share": 0.4262,
      "costPerCall": 0.007094,
      "uniquelyCorrect": 6,
      "proxyId": "qwen3-235b-a22b-thinking-2507"
    },
    {
      "id": "deepseek-ai/DeepSeek-V3.2-TEE",
      "quality": 0.7494,
      "share": 0.1832,
      "costPerCall": 0.001244,
      "uniquelyCorrect": 0,
      "proxyId": "deepseek-v3.1-terminus"
    },
    {
      "id": "Qwen/Qwen3.6-27B-TEE",
      "quality": 0.6953,
      "share": 0.0282,
      "costPerCall": 0.011952,
      "uniquelyCorrect": 8,
      "proxyId": "intern-s1"
    },
    {
      "id": "Qwen/Qwen3.5-397B-A17B-TEE",
      "quality": 0.7651,
      "share": 0.1122,
      "costPerCall": 0.003917,
      "uniquelyCorrect": 3,
      "proxyId": "qwen3-235b-a22b-2507"
    },
    {
      "id": "zai-org/GLM-5.1-TEE",
      "quality": 0.6925,
      "share": 0.0339,
      "costPerCall": 0.00659,
      "uniquelyCorrect": 5,
      "proxyId": "glm-4.6"
    },
    {
      "id": "moonshotai/Kimi-K2.6-TEE",
      "quality": 0.7776,
      "share": 0.1267,
      "costPerCall": 0.003696,
      "uniquelyCorrect": 4,
      "proxyId": "kimi-k2-0905"
    },
    {
      "id": "zai-org/GLM-5.2-TEE",
      "quality": 0.8309,
      "share": 0.0032,
      "costPerCall": 0.027914,
      "uniquelyCorrect": 5,
      "proxyId": "gemini-2.5-pro"
    },
    {
      "id": "moonshotai/Kimi-K3-TEE",
      "quality": 0.8132,
      "share": 0.0137,
      "costPerCall": 0.04267,
      "uniquelyCorrect": 10,
      "proxyId": "gpt-5"
    }
  ] as const;

/** The cost/quality dial, end to end. `savings` is against the frontier model. */
export const FRONTIER_CURVE = [
    {
      "lamCost": 0.0,
      "savings": 0.2343,
      "qualityRetained": 1.0034,
      "modelsUsed": 11
    },
    {
      "lamCost": 0.005,
      "savings": 0.2718,
      "qualityRetained": 1.0034,
      "modelsUsed": 11
    },
    {
      "lamCost": 0.01,
      "savings": 0.3058,
      "qualityRetained": 0.9995,
      "modelsUsed": 11
    },
    {
      "lamCost": 0.02,
      "savings": 0.3597,
      "qualityRetained": 0.9976,
      "modelsUsed": 11
    },
    {
      "lamCost": 0.03,
      "savings": 0.4327,
      "qualityRetained": 1.001,
      "modelsUsed": 11
    },
    {
      "lamCost": 0.05,
      "savings": 0.5322,
      "qualityRetained": 0.9966,
      "modelsUsed": 11
    },
    {
      "lamCost": 0.08,
      "savings": 0.6376,
      "qualityRetained": 0.9971,
      "modelsUsed": 11
    },
    {
      "lamCost": 0.12,
      "savings": 0.7417,
      "qualityRetained": 1.0005,
      "modelsUsed": 11
    },
    {
      "lamCost": 0.2,
      "savings": 0.7969,
      "qualityRetained": 0.9976,
      "modelsUsed": 11
    },
    {
      "lamCost": 0.35,
      "savings": 0.8272,
      "qualityRetained": 0.9781,
      "modelsUsed": 11
    },
    {
      "lamCost": 0.6,
      "savings": 0.8731,
      "qualityRetained": 0.9684,
      "modelsUsed": 10
    },
    {
      "lamCost": 1.0,
      "savings": 0.9119,
      "qualityRetained": 0.9412,
      "modelsUsed": 10
    }
  ] as const;

/**
 * Prices are read from the live Chutes list at decision time and never fitted, so
 * a price change reaches routing with no refit and no redeploy. This is that claim,
 * measured: one model's price is moved and the same trained router re-decides.
 * `estimatorUnchanged` is a byte comparison of the fitted weights either side.
 */
export const PRICE_REACTIVITY = {
  target: "Qwen3 235B Thinking",
  estimatorUnchanged: true,
  liveFetchOk: true,
  catalogueInSync: true,
  points: [
    {
      "factor": 0.25,
      "shareAfter": 0.6053,
      "spendReacting": 3.0669,
      "spendFrozen": 3.5924
    },
    {
      "factor": 0.5,
      "shareAfter": 0.544,
      "spendReacting": 4.6684,
      "spendFrozen": 4.7366
    },
    {
      "factor": 0.75,
      "shareAfter": 0.4794,
      "spendReacting": 6.0198,
      "spendFrozen": 5.8807
    },
    {
      "factor": 1.0,
      "shareAfter": 0.4262,
      "spendReacting": 7.0248,
      "spendFrozen": 7.0248
    },
    {
      "factor": 1.5,
      "shareAfter": 0.3107,
      "spendReacting": 8.5947,
      "spendFrozen": 9.3131
    },
    {
      "factor": 2.0,
      "shareAfter": 0.2244,
      "spendReacting": 9.2447,
      "spendFrozen": 11.6014
    },
    {
      "factor": 4.0,
      "shareAfter": 0.0331,
      "spendReacting": 7.6113,
      "spendFrozen": 20.7545
    }
  ],
  /** Worst case on the grid: what reacting saves against a router that cannot. */
  worstCase: {
    factor: 4.0,
    savedUsd: 13.1431,
    frozenSpendUsd: 20.7545,
    savedShare: 0.6333,
  },
} as const;

/**
 * How much data and how much model the router needs. The second series is the one
 * that matters: validation loss keeps falling with capacity while savings peak
 * earlier, so sizing on the loss curve alone would ship the wrong model.
 */
export const SCALING = {
  learningCurve: [
    {
      "nTrain": 100,
      "valBrier": 0.3645,
      "savings": -0.0115
    },
    {
      "nTrain": 250,
      "valBrier": 0.1968,
      "savings": 0.0884
    },
    {
      "nTrain": 500,
      "valBrier": 0.1735,
      "savings": 0.2079
    },
    {
      "nTrain": 1000,
      "valBrier": 0.1661,
      "savings": 0.1645
    },
    {
      "nTrain": 1500,
      "valBrier": 0.1629,
      "savings": 0.2574
    },
    {
      "nTrain": 2000,
      "valBrier": 0.1614,
      "savings": 0.147
    },
    {
      "nTrain": 2302,
      "valBrier": 0.161,
      "savings": 0.2009
    }
  ],
  capacityCurve: [
    {
      "d": 16,
      "valBrier": 0.1658,
      "savings": 0.1666,
      "artifactKb": 27.7
    },
    {
      "d": 20,
      "valBrier": 0.1638,
      "savings": 0.21,
      "artifactKb": 42.7
    },
    {
      "d": 28,
      "valBrier": 0.163,
      "savings": 0.2394,
      "artifactKb": 82.5
    },
    {
      "d": 36,
      "valBrier": 0.1621,
      "savings": 0.2293,
      "artifactKb": 135.3
    },
    {
      "d": 44,
      "valBrier": 0.162,
      "savings": 0.2157,
      "artifactKb": 201.1
    },
    {
      "d": 52,
      "valBrier": 0.1614,
      "savings": 0.2033,
      "artifactKb": 280.0
    },
    {
      "d": 64,
      "valBrier": 0.161,
      "savings": 0.2009,
      "artifactKb": 422.6
    }
  ],
  bestDByLoss: 64,
  bestDBySavings: 28,
} as const;
