#!/usr/bin/env python
"""Emit `src/lib/measured.ts` — every backend number the site quotes, in one file.

    python scripts/export_measured.py            # print it
    python scripts/export_measured.py --write    # write src/lib/measured.ts

Why a generated module rather than edits to `data.ts`: `data.ts` is copy, owned by
whoever writes the page, and a script that rewrote it would fight them. This file is
*only* measurements, is never hand-edited, and carries the provenance of each number
next to it. The page imports from here and keeps its prose.

Two corpora feed it and they answer different questions, so the module keeps them
apart rather than blending them into one flattering average:

  ROUTERBENCH   11 real commercial models, dated, 36,497 items. Answers "does a
                router go stale, and what does that cost" — the decay curve.
  CHUTES        the 13 models the product serves, proxy-backed. Answers "what does
                routing this pool save today" — savings, traffic mix, price
                reactivity.

Every Chutes-derived field carries `proxyBacked: true` in the module it lands in, so
the caveat cannot be separated from the number by a copy-paste.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

ARTIFACTS = ROOT / "artifacts"
CHUTES = ARTIFACTS / "chutes"
TARGET = ROOT.parent / "src" / "lib" / "measured.ts"


def load(path: Path) -> dict:
    if not path.exists():
        raise SystemExit(f"{path} missing — run `make run` and `make chutes` first")
    return json.loads(path.read_text())


def j(obj) -> str:
    return json.dumps(obj, indent=2).replace("\n", "\n  ")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--every", type=int, default=2, help="sample every Nth week")
    args = ap.parse_args()

    st = load(ARTIFACTS / "staleness.json")
    ov = load(ARTIFACTS / "overview.json")
    pool = load(CHUTES / "01_pool.json")
    calib = load(CHUTES / "04_calibration.json")
    sweep = load(CHUTES / "05_frontier.json")
    policies = load(CHUTES / "06_policies.json")
    analytics = load(CHUTES / "07_analytics.json")
    scaling = load(CHUTES / "09_scaling.json")
    prices = load(CHUTES / "10_prices.json")
    cv = load(CHUTES / "11_crossval.json")

    # ------------------------------------------------------------ decay --
    res, summary = st["result"], st["summary"]
    keep = list(range(0, len(res["weeks"]), args.every))
    decay = {
        "weeks": [res["weeks"][i] for i in keep],
        "frozen": [round(res["arms"]["frozen (A)"]["regret"][i], 3) for i in keep],
        "rolling": [round(res["arms"]["rolling (B)"]["regret"][i], 3) for i in keep],
        "frozenDecay": round(summary["frozen_decay"], 3),
        "rollingDecay": round(summary["rolling_decay"], 3),
        "weekCrossedBelowBestSingle": summary["week_crossed_below_best_single"],
        "shareFromNewModels": round(
            abs(summary["attribution_new_models"])
            / (abs(summary["attribution_new_models"])
               + abs(summary["attribution_fresher_data"])), 3),
    }

    # ----------------------------------------------------------- router --
    router = next(p for p in policies["policies"] if p["policy"] == "router")
    frontier_pol = next(p for p in policies["policies"]
                        if p["policy"].startswith("frontier model"))
    oracle = next(p for p in policies["policies"]
                  if p["policy"] == "oracle (per item, quality)")

    models = [
        {
            "id": m["model_id"],
            "quality": round(m["accuracy"], 4),
            "share": round(m["traffic_share"] or 0.0, 4),
            "costPerCall": round(m["cost_per_call_usd"], 6),
            "uniquelyCorrect": m["uniquely_correct"],
            "proxyId": m["proxy_id"],
        }
        for m in analytics["models"]
    ]

    shock = prices["shock"]
    shock_pts = [
        {
            "factor": p["factor"],
            "shareAfter": round(p["target_share_after"], 4),
            "spendReacting": round(p["spend_after_usd"], 4),
            "spendFrozen": round(p["spend_if_frozen_usd"], 4),
        }
        for p in shock["points"]
    ]
    worst = max(shock["points"], key=lambda p: p["saved_by_reacting_usd"])

    ts = f'''// GENERATED by backend/scripts/export_measured.py — do not edit by hand.
//
// Every number here was produced by a run of the backend and can be traced to an
// artifact under backend/artifacts/. Prose belongs in data.ts; this file is only
// measurements, so that a figure on the page can never drift from the run that
// produced it.
//
// Two corpora, kept apart on purpose:
//
//   ROUTERBENCH — {ov['corpus']['items']:,} real prompts x {ov['corpus']['models']} real commercial models,
//   {ov['corpus']['cells']:,} graded cells, ${ov['corpus']['total_cost_usd']:,.2f} of inference already paid for by
//   whoever collected it. Carries release dates, which is what makes the decay
//   curve a retrospective rather than a simulation.
//
//   CHUTES — the 13 models the product actually routes over. No public benchmark
//   grades those checkpoints, so each slot is bound to a measured stand-in
//   (backend/rollingbench/catalog.py, CHUTES_PROXY) and the router is trained on
//   that model's real per-item outcomes. Prices are the live Chutes list.
//   PROXY-BACKED: read as "what this pool would do if each model behaves like its
//   stand-in", not as a measurement of a Chutes endpoint.

export const ROUTERBENCH = {{
  items: {ov['corpus']['items']},
  models: {ov['corpus']['models']},
  gradedCells: {ov['corpus']['cells']},
  inferenceUsd: {round(ov['corpus']['total_cost_usd'], 2)},
  /** Share of model pairs scoring identically on the same item. */
  tieRate: {round(ov['ties']['pairwise_tie_rate'], 4)},
}} as const;

/**
 * A router fitted once, replayed over 26 weeks of a pool that really grew.
 * `frozen` never updates and cannot select a model released after its cut-off;
 * `rolling` absorbs each week's outcomes and onboards new models. Values are
 * normalised regret against the per-item oracle, so lower is better.
 */
export const DECAY = {j(decay)} as const;

/** The pool the product serves. Proxy-backed — see the header. */
export const CHUTES_POOL = {{
  proxyBacked: true,
  models: {pool['n_train_items'] and len(models)},
  /** Items every one of the 13 answered, used for every comparison below. */
  denseCoreItems: {pool['dense_core_items']},
  testItems: {policies['n_test_items']},
  /**
   * The benchmarks the *dense core* covers — the ones every model answered, and
   * therefore the only ones any comparison here is computed on. Deliberately not
   * `01_pool.json`'s task list, which spans the whole corpus including tasks only
   * the small models were run on; quoting that number would overstate the breadth
   * behind every figure on this page.
   */
  tasks: {j(sorted(t["task"] for t in analytics["tasks"]))},
  /** Every task in the corpus, for context only. Nothing is measured on all of them. */
  corpusTasks: {j(pool['tasks'])},
  /** The dial, calibrated on this pool rather than inherited. */
  lamCost: {calib['chosen_lam_cost']},
}} as const;

/**
 * What routing this pool is worth, over {cv['seeds'] and len(cv['seeds'])} random splits.
 *
 * Two baselines, because they say different things and only quoting the first
 * would flatter the router:
 *
 *   vsFrontierModel — against the highest-quality model, which is what a team
 *   that "just uses the best one" is doing today.
 *
 *   vsBestSingleModel — against the single model that is actually optimal on this
 *   pool once price is counted. A harder opponent, and the honest one. On this
 *   pool it is {policies['best_single_model']}, which beats the
 *   highest-quality model on quality *and* price.
 */
export const SAVINGS = {{
  proxyBacked: true,
  vsFrontierModel: {{
    model: {json.dumps(policies['frontier_model'])},
    savings: {round(cv['savings_vs_frontier']['mean'], 4)},
    savingsSe: {round(cv['savings_vs_frontier']['se'], 4)},
    qualityRetained: {round(cv['quality_vs_frontier']['mean'], 4)},
    qualityRetainedSe: {round(cv['quality_vs_frontier']['se'], 4)},
  }},
  vsBestSingleModel: {{
    model: {json.dumps(policies['best_single_model'])},
    savings: {round(cv['savings_vs_best_single']['mean'], 4)},
    savingsSe: {round(cv['savings_vs_best_single']['se'], 4)},
    qualityRetained: {round(cv['quality_vs_best_single']['mean'], 4)},
    qualityRetainedSe: {round(cv['quality_vs_best_single']['se'], 4)},
  }},
  /** The ceiling: a per-item oracle that always picks the right model. */
  oracleQuality: {round(oracle['quality'], 4)},
  routerQuality: {round(router['quality'], 4)},
  frontierQuality: {round(frontier_pol['quality'], 4)},
  tierMix: {j({k: round(v, 4) for k, v in analytics['tier_mix'].items()})},
}} as const;

/** Per model, on held-out items at the calibrated dial. Proxy-backed. */
export const POOL_MEASURED = {j(models)} as const;

/** The cost/quality dial, end to end. `savings` is against the frontier model. */
export const FRONTIER_CURVE = {j([
    {"lamCost": s["lam_cost"],
     "savings": round(s["savings_vs_frontier"], 4),
     "qualityRetained": round(s["quality_vs_frontier"], 4),
     "modelsUsed": s["models_used"]}
    for s in sweep
])} as const;

/**
 * Prices are read from the live Chutes list at decision time and never fitted, so
 * a price change reaches routing with no refit and no redeploy. This is that claim,
 * measured: one model's price is moved and the same trained router re-decides.
 * `estimatorUnchanged` is a byte comparison of the fitted weights either side.
 */
export const PRICE_REACTIVITY = {{
  target: {json.dumps(shock['target_label'])},
  estimatorUnchanged: {json.dumps(all(p['estimator_unchanged'] for p in shock['points']))},
  liveFetchOk: {json.dumps(prices.get('live_fetch_ok', False))},
  catalogueInSync: {json.dumps(prices.get('diff', {}).get('in_sync', None))},
  points: {j(shock_pts)},
  /** Worst case on the grid: what reacting saves against a router that cannot. */
  worstCase: {{
    factor: {worst['factor']},
    savedUsd: {round(worst['saved_by_reacting_usd'], 4)},
    frozenSpendUsd: {round(worst['spend_if_frozen_usd'], 4)},
    savedShare: {round(worst['saved_by_reacting_usd'] / max(worst['spend_if_frozen_usd'], 1e-9), 4)},
  }},
}} as const;

/**
 * How much data and how much model the router needs. The second series is the one
 * that matters: validation loss keeps falling with capacity while savings peak
 * earlier, so sizing on the loss curve alone would ship the wrong model.
 */
export const SCALING = {{
  learningCurve: {j([
    {"nTrain": r["n_train"],
     "valBrier": round(r["val_brier"], 4),
     "savings": round(r["savings_vs_best_single"], 4)}
    for r in scaling["learning_curve"] if r["repeat"] == 0
])},
  capacityCurve: {j([
    {"d": r["d"], "valBrier": round(r["val_brier"], 4),
     "savings": round(r["savings_vs_best_single"], 4),
     "artifactKb": round(r["artifact_kb"], 1)}
    for r in scaling["capacity_curve"]
])},
  bestDByLoss: {scaling['coupling']['best_d_by_loss']},
  bestDBySavings: {scaling['coupling']['best_d_by_savings']},
}} as const;
'''

    if args.write:
        TARGET.write_text(ts)
        print(f"wrote {TARGET}")
    else:
        print(ts)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
